create table if not exists app_users (
  email text primary key,
  name text not null,
  role text not null,
  last_login_at timestamptz default now()
);

create table if not exists rooms (
  code text primary key,
  title text not null,
  host_name text not null,
  phase text not null default 'lobby',
  current_question_index integer not null default 0,
  created_at timestamptz default now()
);

create table if not exists participants (
  id bigint generated by default as identity primary key,
  room_code text not null references rooms(code) on delete cascade,
  name text not null,
  score integer not null default 0,
  streak integer not null default 0,
  xp integer not null default 0,
  level integer not null default 1,
  joined_at timestamptz default now(),
  unique(room_code, name)
);

alter table participants add column if not exists streak integer not null default 0;
alter table participants add column if not exists xp integer not null default 0;
alter table participants add column if not exists level integer not null default 1;

create table if not exists answers (
  id bigint generated by default as identity primary key,
  room_code text not null references rooms(code) on delete cascade,
  participant_name text not null,
  question_index integer not null,
  answer_index integer not null,
  is_correct boolean not null default false,
  answered_at timestamptz default now(),
  unique(room_code, participant_name, question_index)
);

alter table app_users enable row level security;
alter table rooms enable row level security;
alter table participants enable row level security;
alter table answers enable row level security;

drop policy if exists "app_users_select" on app_users;
drop policy if exists "app_users_insert" on app_users;
drop policy if exists "app_users_update" on app_users;
drop policy if exists "rooms_select" on rooms;
drop policy if exists "rooms_insert" on rooms;
drop policy if exists "rooms_update" on rooms;
drop policy if exists "participants_select" on participants;
drop policy if exists "participants_insert" on participants;
drop policy if exists "participants_update" on participants;
drop policy if exists "answers_select" on answers;
drop policy if exists "answers_insert" on answers;
drop policy if exists "answers_update" on answers;

create policy "app_users_select" on app_users for select using (true);
create policy "app_users_insert" on app_users for insert with check (true);
create policy "app_users_update" on app_users for update using (true);

create policy "rooms_select" on rooms for select using (true);
create policy "rooms_insert" on rooms for insert with check (true);
create policy "rooms_update" on rooms for update using (true);

create policy "participants_select" on participants for select using (true);
create policy "participants_insert" on participants for insert with check (true);
create policy "participants_update" on participants for update using (true);

create policy "answers_select" on answers for select using (true);
create policy "answers_insert" on answers for insert with check (true);
create policy "answers_update" on answers for update using (true);

create table if not exists room_questions (
  id bigint generated by default as identity primary key,
  room_code text not null references rooms(code) on delete cascade,
  sort_order integer not null,
  question text not null,
  options jsonb not null default '[]'::jsonb,
  correct_index integer not null default 0,
  explanation text not null default '',
  category text not null default 'Umum',
  points integer not null default 100,
  color_value integer not null default 4280688358,
  unique(room_code, sort_order)
);

create table if not exists quiz_results (
  id bigint generated by default as identity primary key,
  room_code text not null references rooms(code) on delete cascade,
  participant_name text not null,
  total_score integer not null default 0,
  correct_answers integer not null default 0,
  wrong_answers integer not null default 0,
  percentage numeric not null default 0,
  grade text not null default 'D',
  completed_at timestamptz default now(),
  unique(room_code, participant_name)
);

alter table room_questions enable row level security;
alter table quiz_results enable row level security;

drop policy if exists "room_questions_select" on room_questions;
drop policy if exists "room_questions_insert" on room_questions;
drop policy if exists "room_questions_update" on room_questions;
drop policy if exists "room_questions_delete" on room_questions;
drop policy if exists "quiz_results_select" on quiz_results;
drop policy if exists "quiz_results_insert" on quiz_results;
drop policy if exists "quiz_results_update" on quiz_results;

create policy "room_questions_select" on room_questions for select using (true);
create policy "room_questions_insert" on room_questions for insert with check (true);
create policy "room_questions_update" on room_questions for update using (true);
create policy "room_questions_delete" on room_questions for delete using (true);

create policy "quiz_results_select" on quiz_results for select using (true);
create policy "quiz_results_insert" on quiz_results for insert with check (true);
create policy "quiz_results_update" on quiz_results for update using (true);
