create table if not exists app_users (
  email text primary key,
  name text not null,
  role text not null,
  last_login_at timestamptz default now()
);

create table if not exists rooms (
  code text primary key,
  title text not null,
  host_name text not null,
  phase text not null default 'lobby',
  current_question_index integer not null default 0,
  created_at timestamptz default now()
);

create table if not exists participants (
  id bigint generated by default as identity primary key,
  room_code text not null references rooms(code) on delete cascade,
  name text not null,
  score integer not null default 0,
  joined_at timestamptz default now(),
  unique(room_code, name)
);

create table if not exists answers (
  id bigint generated by default as identity primary key,
  room_code text not null references rooms(code) on delete cascade,
  participant_name text not null,
  question_index integer not null,
  answer_index integer not null,
  is_correct boolean not null default false,
  answered_at timestamptz default now(),
  unique(room_code, participant_name, question_index)
);

alter table app_users enable row level security;
alter table rooms enable row level security;
alter table participants enable row level security;
alter table answers enable row level security;

create policy "allow anon read app_users" on app_users for select using (true);
create policy "allow anon write app_users" on app_users for insert with check (true);
create policy "allow anon update app_users" on app_users for update using (true);

create policy "allow anon read rooms" on rooms for select using (true);
create policy "allow anon write rooms" on rooms for insert with check (true);
create policy "allow anon update rooms" on rooms for update using (true);

create policy "allow anon read participants" on participants for select using (true);
create policy "allow anon write participants" on participants for insert with check (true);
create policy "allow anon update participants" on participants for update using (true);

create policy "allow anon read answers" on answers for select using (true);
create policy "allow anon write answers" on answers for insert with check (true);
create policy "allow anon update answers" on answers for update using (true);
